<?php
/**
 * Server-side rendering of the blockshot/svg block.
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block default content.
 * @var WP_Block $block      Block instance.
 */

declare(strict_types=1);

$svg_content = $attributes['content'] ?? '';

if (empty(trim($svg_content))) {
	return;
}

$allowed_svg_tags = [
	'svg'            => [
		'xmlns'       => true,
		'viewbox'     => true,
		'width'       => true,
		'height'      => true,
		'fill'        => true,
		'stroke'      => true,
		'class'       => true,
		'id'          => true,
		'role'        => true,
		'aria-hidden' => true,
		'aria-label'  => true,
		'focusable'   => true,
		'style'       => true,
		'xmlns:xlink' => true,
	],
	'g'              => [
		'fill'        => true,
		'stroke'      => true,
		'transform'   => true,
		'class'       => true,
		'id'          => true,
		'opacity'     => true,
		'style'       => true,
		'clip-path'   => true,
		'mask'        => true,
	],
	'path'           => [
		'd'               => true,
		'fill'            => true,
		'stroke'          => true,
		'stroke-width'    => true,
		'stroke-linecap'  => true,
		'stroke-linejoin' => true,
		'stroke-dasharray' => true,
		'stroke-dashoffset' => true,
		'stroke-opacity'  => true,
		'fill-rule'       => true,
		'fill-opacity'    => true,
		'clip-rule'       => true,
		'transform'       => true,
		'class'           => true,
		'id'              => true,
		'opacity'         => true,
		'style'           => true,
	],
	'circle'         => [
		'cx'          => true,
		'cy'          => true,
		'r'           => true,
		'fill'        => true,
		'stroke'      => true,
		'stroke-width' => true,
		'transform'   => true,
		'class'       => true,
		'id'          => true,
		'opacity'     => true,
		'style'       => true,
	],
	'ellipse'        => [
		'cx'          => true,
		'cy'          => true,
		'rx'          => true,
		'ry'          => true,
		'fill'        => true,
		'stroke'      => true,
		'stroke-width' => true,
		'transform'   => true,
		'class'       => true,
		'id'          => true,
		'opacity'     => true,
		'style'       => true,
	],
	'rect'           => [
		'x'           => true,
		'y'           => true,
		'width'       => true,
		'height'      => true,
		'rx'          => true,
		'ry'          => true,
		'fill'        => true,
		'stroke'      => true,
		'stroke-width' => true,
		'transform'   => true,
		'class'       => true,
		'id'          => true,
		'opacity'     => true,
		'style'       => true,
	],
	'line'           => [
		'x1'          => true,
		'y1'          => true,
		'x2'          => true,
		'y2'          => true,
		'stroke'      => true,
		'stroke-width' => true,
		'stroke-linecap' => true,
		'stroke-dasharray' => true,
		'transform'   => true,
		'class'       => true,
		'id'          => true,
		'opacity'     => true,
		'style'       => true,
	],
	'polyline'       => [
		'points'      => true,
		'fill'        => true,
		'stroke'      => true,
		'stroke-width' => true,
		'stroke-linecap' => true,
		'stroke-linejoin' => true,
		'transform'   => true,
		'class'       => true,
		'id'          => true,
		'opacity'     => true,
		'style'       => true,
	],
	'polygon'        => [
		'points'      => true,
		'fill'        => true,
		'stroke'      => true,
		'stroke-width' => true,
		'stroke-linecap' => true,
		'stroke-linejoin' => true,
		'fill-rule'   => true,
		'transform'   => true,
		'class'       => true,
		'id'          => true,
		'opacity'     => true,
		'style'       => true,
	],
	'text'           => [
		'x'              => true,
		'y'              => true,
		'dx'             => true,
		'dy'             => true,
		'text-anchor'    => true,
		'font-size'      => true,
		'font-family'    => true,
		'font-weight'    => true,
		'fill'           => true,
		'stroke'         => true,
		'transform'      => true,
		'dominant-baseline' => true,
		'class'          => true,
		'id'             => true,
		'opacity'        => true,
		'style'          => true,
	],
	'tspan'          => [
		'x'           => true,
		'y'           => true,
		'dx'          => true,
		'dy'          => true,
		'fill'        => true,
		'font-size'   => true,
		'font-family' => true,
		'font-weight' => true,
		'class'       => true,
		'id'          => true,
		'style'       => true,
	],
	'defs'           => [],
	'clippath'       => [
		'id'              => true,
		'clippathunits'   => true,
		'transform'       => true,
	],
	'mask'           => [
		'id'          => true,
		'x'           => true,
		'y'           => true,
		'width'       => true,
		'height'      => true,
		'maskunits'   => true,
		'maskcontentunits' => true,
	],
	'use'            => [
		'href'        => true,
		'xlink:href'  => true,
		'x'           => true,
		'y'           => true,
		'width'       => true,
		'height'      => true,
		'transform'   => true,
		'class'       => true,
		'id'          => true,
		'style'       => true,
	],
	'symbol'         => [
		'id'          => true,
		'viewbox'     => true,
		'width'       => true,
		'height'      => true,
	],
	'title'          => [],
	'desc'           => [],
	'lineargradient' => [
		'id'                => true,
		'x1'               => true,
		'y1'               => true,
		'x2'               => true,
		'y2'               => true,
		'gradientunits'    => true,
		'gradienttransform' => true,
		'spreadmethod'     => true,
	],
	'radialgradient' => [
		'id'                => true,
		'cx'               => true,
		'cy'               => true,
		'r'                => true,
		'fx'               => true,
		'fy'               => true,
		'gradientunits'    => true,
		'gradienttransform' => true,
		'spreadmethod'     => true,
	],
	'stop'           => [
		'offset'       => true,
		'stop-color'   => true,
		'stop-opacity' => true,
		'style'        => true,
	],
	'filter'         => [
		'id'              => true,
		'x'               => true,
		'y'               => true,
		'width'           => true,
		'height'          => true,
		'filterunits'     => true,
		'primitiveunits'  => true,
	],
	'fegaussianblur' => [
		'in'           => true,
		'stddeviation' => true,
		'result'       => true,
	],
	'feoffset'       => [
		'in'     => true,
		'dx'     => true,
		'dy'     => true,
		'result' => true,
	],
	'femerge'        => [],
	'femergenode'    => [
		'in' => true,
	],
	'fecolormatrix'  => [
		'in'     => true,
		'type'   => true,
		'values' => true,
		'result' => true,
	],
	'feblend'        => [
		'in'     => true,
		'in2'    => true,
		'mode'   => true,
		'result' => true,
	],
	'feflood'        => [
		'flood-color'   => true,
		'flood-opacity' => true,
		'result'        => true,
	],
	'fecomposite'    => [
		'in'       => true,
		'in2'      => true,
		'operator' => true,
		'k1'       => true,
		'k2'       => true,
		'k3'       => true,
		'k4'       => true,
		'result'   => true,
	],
	'pattern'        => [
		'id'                  => true,
		'x'                   => true,
		'y'                   => true,
		'width'               => true,
		'height'              => true,
		'patternunits'        => true,
		'patterncontentunits' => true,
		'patterntransform'    => true,
		'viewbox'             => true,
	],
	'image'          => [
		'href'              => true,
		'xlink:href'        => true,
		'x'                 => true,
		'y'                 => true,
		'width'             => true,
		'height'            => true,
		'preserveaspectratio' => true,
	],
	'animate'        => [
		'attributename' => true,
		'from'          => true,
		'to'            => true,
		'dur'           => true,
		'repeatcount'   => true,
		'fill'          => true,
		'begin'         => true,
		'values'        => true,
		'keytimes'      => true,
		'calcmode'      => true,
	],
	'animatetransform' => [
		'attributename' => true,
		'type'          => true,
		'from'          => true,
		'to'            => true,
		'dur'           => true,
		'repeatcount'   => true,
		'fill'          => true,
		'begin'         => true,
		'values'        => true,
	],
];

$sanitized = wp_kses($svg_content, $allowed_svg_tags);

if (empty(trim($sanitized))) {
	return;
}

printf(
	'<div %s>%s</div>',
	get_block_wrapper_attributes(),
	$sanitized
);
